### ISSUE TITLE
Add Corsa exhaust

### ISSUE THREAD

**Issue by barm** [86challenge/rules#20]
2.5 pipe diameter and muffler, but we don't know the weight yet:
https://www.corsaperformance.com/products/2-5-sport-cat-back-14864

**Comment by therumblewagon** [comment]
@barm email from Corsa, assuming this is shipping weight given they included dimensions. Will confirm  

<img width="368" alt="Corsa exhaust weight" src="https://github.com/user-attachments/assets/40b9cb69-4857-4b56-909e-be28f472e878">

**Comment by barm** [comment]
This just tells us that the weight of the exhaust is not less than 53 lbs but it doesn’t actually tell us what the exhaust weighs.

**Comment by therumblewagon** [comment]
Fair point - have emailed them again for clarification Sent from my iPhoneOn Nov 6, 2024, at 12:01, Brian Armstrong ***@***.***> wrote:﻿
This just tells us that the weight of the exhaust is not less than 53 lbs but it doesn’t actually tell us what the exhaust weighs.
