### ISSUE TITLE
17” SX2 to 0 points

### ISSUE THREAD

**Issue by itsmang0** [86challenge/rules#37]
SX2s are favored with handicap and points. 
17” SX2 (-1) + Big Front Areo (+1.5) + Big Rear Areo (+1.5) = 2 points
Any 2pt tire = 2 points + handy cap 
(Specifically concerned for SX2s in touring)

**Comment by itsmang0** [comment]
90% of Street Class drivers won’t be affected if 17” SX2s are 0 points.
Since most build costs are 2 points.
Gen2 (+2) + Suspension (+1) = 3 points
(Street Class Limit is 3 points)

**Comment by wlorne** [comment]
> SX2s are favored with handicap and points. 17” SX2 (-1) + Big Front Areo (+1.5) + Big Rear Areo (+1.5) = 2 points Any 2pt tire = 2 points + handy cap (Specifically concerned for SX2s in touring)

Disagree. This is unrealistic setup for touring. Aero would not work with stock spring rates/dampers, which would require taking points for stiffer springs - but realistically you'd need a 1pt coilover setup at very least.

**Comment by wlorne** [comment]
> Or change handicap to waive first 3 points since that’s what street class allows up to.

This is in new Touring rules for 2025

**Comment by wlorne** [comment]
> 90% of Street Class drivers won’t be affected if 17” SX2s are 0 points. Since most build costs are 2 points. Gen2 (+2) + Suspension (+1) = 3 points (Street Class Limit is 3 points)

Disagree. Many Gen 2 owners are experimenting with additional mods besides coilovers that would push them out of street if this change were to go through. This would basically make Street a "Stock +" class with limited freedom for modifications.

**Comment by zeroomega** [comment]
17inch SX2 with big front and rear aero is very unlikely to gain more than a 2pt 200tw tire. The SX2s has bad load sensitivity and with 86's power output, big aero has considerable regression on straight line performance. 
If not for cost and convenience reasons. I would prefer to have 2pt power mod than 2pt aero.

Besides, SXs are current sponsor's tire choice for the series. If there is no incentives to run them, The sponsor will be unhappy.

**Comment by barm** [comment]
No changes for SX2 points for 2025.
